action.configuration.civiremote_match_contact_action:
  type: action_configuration_default
  label: 'CiviRemote: Match contact(s)'
action.configuration.civiremote_synchronise_roles_action:
  type: action_configuration_default
  label: 'CiviRemote: Synchronise CiviRemote roles'
